version: "2.1"
services:
  haniflix_backend:
    build: .
    environment:
      NODE_ENV: production
    container_name: haniflix_backend
    working_dir: /usr/app
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    ports:
      - 8800:8800
    restart: unless-stopped
    command: node index.js
